title: Phazerville Suite for O_C
description: The Phazerville Suite is an open-source firmware project for the Ornament & Crime Eurorack module
show_downloads: true
theme: jekyll-theme-midnight
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
