title: Phazerville Suite for O_C
description: The Phazerville Suite is an open-source firmware project for the Ornament & Crime Eurorack module
show_downloads: true
remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
