title: Phazerville Suite for O_C
description: An open-source firmware project for the Ornament & Crime Eurorack module
remote_theme: just-the-docs/just-the-docs@v0.8.2
color_scheme: dark
permalink: "/:name"

defaults:
  scope:
    path: "*.md"
  values:
    layout: default

aux_links:
  "Downloads":
    - "https://github.com/djphazer/O_C-Phazerville/releases"
nav_external_links:
  - title: Custom Firmware Builds
    url: https://github.com/djphazer/O_C-Phazerville/discussions/38
    opens_in_new_tab: true

collections:
  apps:
    permalink: "/:name"
    output: true
  applets:
    permalink: "/:name"
    output: true

just_the_docs:
  collections:
    apps:
      name: Apps
      nav_fold: true
    applets:
      name: Applets
      nav_fold: true

footer_content: "This documentation is part of the <a href=\"https://github.com/djphazer/O_C-Phazerville\">Phazerville Suite O_C firmware project</a>, published with Github Pages"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/djphazer/O_C-Phazerville" # the github URL for your repo
gh_edit_branch: "wiki-docs" # the branch that your docs is served from

