title: Phazerville Suite for O_C
description: An open-source firmware project for the Ornament & Crime Eurorack module
remote_theme: just-the-docs/just-the-docs@v0.8.2
color_scheme: dark
permalink: "/:name"

aux_links:
  "Downloads":
    - "https://github.com/djphazer/O_C-Phazerville/releases"
nav_external_links:
  - title: Custom Firmware Builds
    url: https://github.com/djphazer/O_C-Phazerville/discussions/38
    opens_in_new_tab: true

collections:
  apps:
    permalink: "/:name"
    output: true
  applets:
    permalink: "/:name"
    output: true

just_the_docs:
  collections:
    apps:
      name: Apps
      nav_fold: true
    applets:
      name: Applets
      nav_fold: true
